services:
    postgres:
        image: 'postgres:15.2'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        ports:
            - 9098:9098
